/**
 * Animation registry — catalog of all converted animations.
 */
export const animations = [
  {
    slug: 'angle',
    name: 'Angle',
    category: 'fractal',
    module: () => import('./animations/fractal/angle.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'fractal-cover',
    name: 'Fractal Cover',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-cover.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-engin43',
    name: 'Fractal Engin43',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-engin43.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-engine',
    name: 'Fractal Engine',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-engine.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor',
    name: 'Fractal Experamentor',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor2',
    name: 'Fractal Experamentor2',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor21',
    name: 'Fractal Experamentor21',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor21.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor22',
    name: 'Fractal Experamentor22',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor22.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor23',
    name: 'Fractal Experamentor23',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor23.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor4',
    name: 'Fractal Experamentor4',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-experamentor5',
    name: 'Fractal Experamentor5',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-experamentor5.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-fire',
    name: 'Fractal Fire',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-fire.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-fire2',
    name: 'Fractal Fire2',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-fire2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-grower',
    name: 'Fractal Grower',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-grower.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-menu4',
    name: 'Fractal Menu4',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-menu4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-menu5',
    name: 'Fractal Menu5',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-menu5.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-menu6',
    name: 'Fractal Menu6',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-menu6.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'fractal-somthing3',
    name: 'Fractal Somthing3',
    category: 'fractal',
    module: () => import('./animations/fractal/fractal-somthing3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'hanging-tree',
    name: 'Hanging Tree',
    category: 'fractal',
    module: () => import('./animations/fractal/hanging-tree.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'inner-fractal',
    name: 'Inner Fractal',
    category: 'fractal',
    module: () => import('./animations/fractal/inner-fractal.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'inner-fractal10',
    name: 'Inner Fractal10',
    category: 'fractal',
    module: () => import('./animations/fractal/inner-fractal10.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'inner-fractal2',
    name: 'Inner Fractal2',
    category: 'fractal',
    module: () => import('./animations/fractal/inner-fractal2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'inner-fractal4',
    name: 'Inner Fractal4',
    category: 'fractal',
    module: () => import('./animations/fractal/inner-fractal4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'inner-fractal5',
    name: 'Inner Fractal5',
    category: 'fractal',
    module: () => import('./animations/fractal/inner-fractal5.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'inner-fractal9',
    name: 'Inner Fractal9',
    category: 'fractal',
    module: () => import('./animations/fractal/inner-fractal9.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'justline',
    name: 'Justline',
    category: 'fractal',
    module: () => import('./animations/fractal/justline.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'tri-fractal2',
    name: 'Tri Fractal2',
    category: 'fractal',
    module: () => import('./animations/fractal/tri-fractal2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'wave-fractal-waver',
    name: 'Wave Fractal Waver',
    category: 'fractal',
    module: () => import('./animations/fractal/wave-fractal-waver.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'waving-fractal',
    name: 'Waving Fractal',
    category: 'fractal',
    module: () => import('./animations/fractal/waving-fractal.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: '2-menu',
    name: '2 Menu',
    category: 'graph',
    module: () => import('./animations/graph/2-menu.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: '3',
    name: '3',
    category: 'graph',
    module: () => import('./animations/graph/3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: '5',
    name: '5',
    category: 'graph',
    module: () => import('./animations/graph/5.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: '6-black',
    name: '6 Black',
    category: 'graph',
    module: () => import('./animations/graph/6-black.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'angle-test',
    name: 'Angle Test',
    category: 'graph',
    module: () => import('./animations/graph/angle-test.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'gradients',
    name: 'Gradients',
    category: 'graph',
    module: () => import('./animations/graph/gradients.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'so-sea-sick-11',
    name: 'So Sea Sick 11',
    category: 'graph',
    module: () => import('./animations/graph/so-sea-sick-11.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'so-sea-sick-2',
    name: 'So Sea Sick 2',
    category: 'graph',
    module: () => import('./animations/graph/so-sea-sick-2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'vibrations',
    name: 'Vibrations',
    category: 'graph',
    module: () => import('./animations/graph/vibrations.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'url-kscope06',
    name: 'Url Kscope06',
    category: 'kscope',
    module: () => import('./animations/kscope/url-kscope06.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: '16-arms',
    name: '16 Arms',
    category: 'lab',
    module: () => import('./animations/lab/16-arms.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: '4-circles-01',
    name: '4 Circles 01',
    category: 'lab',
    module: () => import('./animations/lab/4-circles-01.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'hell-going',
    name: 'Hell Going',
    category: 'lab',
    module: () => import('./animations/lab/hell-going.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'polartwilight',
    name: 'Polartwilight',
    category: 'lab',
    module: () => import('./animations/lab/polartwilight.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'square-spiral',
    name: 'Square Spiral',
    category: 'lab',
    module: () => import('./animations/lab/square-spiral.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide',
    name: 'Superslide',
    category: 'lab',
    module: () => import('./animations/lab/superslide.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'trifractal01',
    name: 'Trifractal01',
    category: 'lab',
    module: () => import('./animations/lab/trifractal01.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'trifractal02',
    name: 'Trifractal02',
    category: 'lab',
    module: () => import('./animations/lab/trifractal02.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'wave-fractal',
    name: 'Wave Fractal',
    category: 'lab',
    module: () => import('./animations/lab/wave-fractal.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ballers11',
    name: 'Ballers11',
    category: 'random',
    module: () => import('./animations/random/ballers11.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'churning3',
    name: 'Churning 3',
    category: 'random',
    module: () => import('./animations/random/churning3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'engine',
    name: 'Engine',
    category: 'random',
    module: () => import('./animations/random/engine.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'fern',
    name: 'Fern',
    category: 'random',
    module: () => import('./animations/random/fern.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ganjascope',
    name: 'Ganjascope',
    category: 'random',
    module: () => import('./animations/random/ganjascope.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'having-a-laugh4',
    name: 'Having A Laugh4',
    category: 'random',
    module: () => import('./animations/random/having-a-laugh4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'home-phong-busted',
    name: 'Home Phong Busted',
    category: 'random',
    module: () => import('./animations/random/home-phong-busted.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'horiball11',
    name: 'Horiball11',
    category: 'random',
    module: () => import('./animations/random/horiball11.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'infinitytest02',
    name: 'Infinitytest02',
    category: 'random',
    module: () => import('./animations/random/infinitytest02.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'intertrip3',
    name: 'Intertrip3',
    category: 'random',
    module: () => import('./animations/random/intertrip3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'intertrip666',
    name: 'Intertrip666',
    category: 'random',
    module: () => import('./animations/random/intertrip666.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'intro1',
    name: 'Intro1',
    category: 'random',
    module: () => import('./animations/random/intro1.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'musicaltengent2',
    name: 'Musicaltengent2',
    category: 'random',
    module: () => import('./animations/random/musicaltengent2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'particle1-orange2',
    name: 'Particle1 Orange2',
    category: 'random',
    module: () => import('./animations/random/particle1-orange2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'particles14-new-colors',
    name: 'Particles14 New Colors',
    category: 'random',
    module: () => import('./animations/random/particles14-new-colors.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'sine',
    name: 'Sine',
    category: 'random',
    module: () => import('./animations/random/sine.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'stay7',
    name: 'Stay7',
    category: 'random',
    module: () => import('./animations/random/stay7.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'threed4',
    name: 'Threed4',
    category: 'random',
    module: () => import('./animations/random/threed4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'wtf2',
    name: 'Wtf2',
    category: 'random',
    module: () => import('./animations/random/wtf2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler10',
    name: 'Ringler 10',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler10.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler11',
    name: 'Ringler11',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler11.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler12',
    name: 'Ringler12',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler12.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler13',
    name: 'Ringler13',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler13.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler13-colored',
    name: 'Ringler13 Colored',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler13-colored.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler17',
    name: 'Ringler17',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler17.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler18',
    name: 'Ringler18',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler18.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler2-3',
    name: 'Ringler2 3',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler2-3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler2-36',
    name: 'Ringler2 36',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler2-36.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler2-37',
    name: 'Ringler2 37',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler2-37.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler2-38',
    name: 'Ringler2 38',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler2-38.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler2-39',
    name: 'Ringler2 39',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler2-39.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler2-43',
    name: 'Ringler2 43',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler2-43.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler8',
    name: 'Ringler8',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler8.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'ringler9',
    name: 'Ringler9',
    category: 'ringler',
    module: () => import('./animations/ringler/ringler9.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'spiraltest',
    name: 'Spiraltest',
    category: 'ringler',
    module: () => import('./animations/ringler/spiraltest.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'drawing2',
    name: 'Drawing 2',
    category: 'spiral',
    module: () => import('./animations/spiral/drawing2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'drawing3',
    name: 'Drawing3',
    category: 'spiral',
    module: () => import('./animations/spiral/drawing3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'drawing4',
    name: 'Drawing4',
    category: 'spiral',
    module: () => import('./animations/spiral/drawing4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'drawing7',
    name: 'Drawing7',
    category: 'spiral',
    module: () => import('./animations/spiral/drawing7.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide11',
    name: 'Superslide11',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide11.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide12',
    name: 'Superslide12',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide12.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide2',
    name: 'Superslide 2',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide2.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide3',
    name: 'Superslide3',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide3.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide4',
    name: 'Superslide4',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide4.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide7',
    name: 'Superslide7',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide7.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide8',
    name: 'Superslide8',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide8.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'superslide9',
    name: 'Superslide9',
    category: 'superslide',
    module: () => import('./animations/superslide/superslide9.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'epileptics-beware',
    name: 'Epileptics Beware',
    category: 'swfs',
    module: () => import('./animations/swfs/epileptics-beware.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
  {
    slug: 'spiralling-waves',
    name: 'Spiralling Waves',
    category: 'swfs',
    module: () => import('./animations/swfs/spiralling-waves.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#0a0e1a',
  },
  {
    slug: 'violent-orange',
    name: 'Violent Orange',
    category: 'swfs',
    module: () => import('./animations/swfs/violent-orange.js'),
    stageWidth: 550,
    stageHeight: 400,
    bgColor: '#000000',
  },
];

export function getAnimation(slug) {
  return animations.find(a => a.slug === slug) || null;
}

export function getCategories() {
  return [...new Set(animations.map(a => a.category))].sort();
}

export function getModulePath(entry) {
  const match = entry.module.toString().match(/import\(['"](.+?)['"]\)/);
  if (!match) return null;
  return match[1].replace('./', '/src/');
}
